---
- name: Detect and Execute OS-specific tasks
  #hosts: "{{host_list}}"
  hosts: all  
  gather_facts: yes
  vars:
    whitelist_add_users: "{{ add_users | default('') }}"
    whitelist_add_groups: "{{ add_groups| default('') }}"    
    whitelist_remove_users: "{{ remove_users | default('') }}"
    whitelist_remove_groups: "{{ remove_groups| default('') }}"
  
  ## Section to add specific users & Group from Whitelisting ##
  tasks:
  - name: Add users to whitelist
    shell: realm permit {{ whitelist_add_users }}
    when: whitelist_add_users != ''
    register: add_users_output
    
  - name: Add groups to whitelist
    shell: realm permit -g {{ whitelist_add_groups }}
    when: whitelist_add_groups != ''
    register: add_groups_output
  
  ## Section to remove specific users & Group from Whitelisting ##
  - name: Remove users from whitelist
    shell: realm deny {{ whitelist_remove_users }}
    when: whitelist_remove_users != ''
    register: remove_users_output
    
  - name: Remove groups from whitelist
    shell: realm deny -g {{ whitelist_remove_groups }}
    when: whitelist_remove_groups != ''
    register: remove_groups_output
    
  - name: Display results
    debug:
      msg: |
        Users added: {{ whitelist_add_users if whitelist_add_users != '' else 'None' }}
        Groups added: {{ whitelist_add_groups if whitelist_add_groups != '' else 'None' }}
        Users removed: {{ whitelist_remove_users if whitelist_remove_users != '' else 'None' }}
        Groups removed: {{ whitelist_remove_groups if whitelist_remove_groups != '' else 'None' }}
...
